apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bct7
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0057-tenant/tkrw-pr712-0075-0057-app/devfile-sample-bct7@sha256:8e9ddcf8cecebcd4411446ba8903fcc3351aa2bb6da7879226166c5f5c32b997
        name: my-nodejs
        resources: {}
status: {}
